import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { checkComposition, prepareComposition, prepareRecoveredComposition, readCompositionState, restoreRenderer, validateComposition, validateFragmentSet } from "../scripts/compose-carousel.mjs";
import { exportRun, inspectDom, pngSize, scanHtml } from "../scripts/export-carousel.mjs";
import { loadArchive, validateLayout } from "../scripts/validate-carousel-layout.mjs";

const png = Buffer.from("89504e470d0a1a0a0000000d4948445200000438000005460806000000000000", "hex");
const contentValues = [
  { type:"statement", text:"A & B remains less than 3 < 4." },
  { type:"collection", items:[{ label:"Commit", detail:"Keep writes." },{ label:"Rollback", detail:"Discard writes." }] },
  { type:"comparison", sides:[{ label:"Commit", items:["Both rows"] },{ label:"Rollback", items:["Neither row"] }] },
  { type:"sequence", steps:[{ label:"Debit", detail:"Change one row." },{ label:"Credit", detail:"Change the other." }] },
  { type:"example", setup:"Move ten credits.", code:"BEGIN;\nUPDATE accounts;", explanation:"One boundary owns both writes." },
  { type:"checklist", items:[{ label:"Begin", detail:"Open a transaction." },{ label:"Finish", detail:"Commit or roll back." }] },
];
function fixture(count = 7, { root = mkdtempSync(join(tmpdir(), "apollo-render-")), runId = `run-${count}` } = {}) {
  const run = join(root, "runs", runId), stateFile = join(root, `${runId}-composition-state.json`), roles = ["hook", "overview", ...Array.from({ length:count - 3 }, (_, index) => ["concept", "example", "deep-dive", "interview"][index % 4]), "takeaway"];
  mkdirSync(run, { recursive:true }); const content = { topic:"ACID", slides:roles.map((role, index) => ({ number:index + 1, role, title:`Slide ${index + 1}`, why:"This explains a concrete database decision.", glossary:[{ term:"Transaction", definition:"A unit of database work." }], content:structuredClone(contentValues[index % contentValues.length]) })) };
  const layout = { template:"database-blueprint", motif:"blueprint", slides:content.slides.map(slide => ({ number:slide.number, composition:slide.content.type === "sequence" ? "flow" : "focus", density:"standard", visualAnchor:"headline", direction:"top-down", directionNote:`Lead through slide ${slide.number}.` })) };
  writeFileSync(join(run, "request.json"), JSON.stringify({ topic:"ACID", runId, createdAt:"2026-07-16T00:00:00.000Z", model:"gpt-5.6-terra", effort:"medium" })); writeFileSync(join(run, "carousel-content.json"), JSON.stringify(content)); writeFileSync(join(run, "carousel-layout.json"), JSON.stringify(layout)); return { root, run, stateFile, content, layout };
}
function fragment(_slide, _plan) { return '<section class="free-flow" style="display:flex;height:100%;flex-direction:column;justify-content:space-between"><article class="novel-card"><h3>Agent-authored body</h3><p>Fresh supporting copy &amp; context.</p></article><blockquote style="border-left-width:2px;border-left-style:solid;border-left-color:#1460AA;padding:8px">Interview signal</blockquote></section>'; }
function svgFragment(_slide, _plan, shapes = '<line class="diagram-line" style="stroke:#1460AA;stroke-width:2" x1="0" y1="0" x2="1000" y2="600"></line>') { return `<figure class="free-diagram"><p>Local geometry</p><svg class="diagram-canvas" viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false">${shapes}</svg></figure>`; }
const spanSvg = percent => `<svg style="display:block;width:100%;height:${percent}%" viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><rect style="fill:#123" x="0" y="0" width="1000" height="600"></rect></svg>`;
const shallow = '<div style="display:flex;height:20px"><p>Short strip</p><p>does not span</p></div>';
const wrapper = '<div style="display:block;position:relative;height:100%;background-color:#123"><p style="position:absolute;top:0;left:0">One small label</p></div>';
const bodyPath = (value, index = 0) => join(value.run, "slide-bodies", `${String(index + 1).padStart(2, "0")}.html`);
function writeFragments(value) { value.content.slides.forEach((slide, index) => writeFileSync(join(value.run, "slide-bodies", `${String(index + 1).padStart(2, "0")}.html`), fragment(slide, value.layout.slides[index]))); }
function prepared(count = 7, options) { const value = fixture(count, options); prepareComposition(value.run, value.stateFile); writeFragments(value); return value; }
async function rejected(task) { try { await task(); } catch (error) { return error; } assert.fail("expected rejection"); }
function fakeChromium({ count = 7, violation = [], screenshotError = false, image = png, onMeasure = () => {}, onSetContent = () => {}, onScreenshot = () => {} } = {}) { return { launch:async () => ({ newPage:async () => ({ route:async () => {}, setContent:async html => onSetContent(html), evaluate:async fn => { if (!String(fn).includes("document.fonts.ready")) return { width:1080, height:1350 }; onMeasure(); return { roots:count, slides:Array.from({ length:count }, (_, index) => String(index + 1)), violations:violation }; }, locator:selector => ({ evaluate:async () => ({ width:1080, height:1350 }), screenshot:async ({ path }) => { const slide = Number(selector.match(/data-slide="(\d+)"/)?.[1]); await onScreenshot({ path, slide }); if (screenshotError) throw Error("shot"); writeFileSync(path, image); } }) }), close:async () => {} }) }; }

test("accepts free-flow bodies while preserving 7/10 fixed-shell copy", () => { for (const count of [7, 10]) { const value = prepared(count), result = validateComposition(value.run, readCompositionState(value.run, value.stateFile)); assert.equal(result.fragments.length, count); assert.match(result.html, /Agent-authored body/); assert.match(result.html, /ACID/); assert.match(result.html, /Slide 1/); assert.match(result.html, /This explains a concrete database decision/); assert.match(result.html, /Transaction/); assert.equal((result.html.match(/class="slide-body"/g) ?? []).length, count); scanHtml(result.html, count); } });
test("allows body h2 while the fixed shell retains its h1", () => { const value = prepared(); writeFileSync(bodyPath(value), "<h2>Body section</h2><p>Supporting copy.</p>"); const result = validateComposition(value.run, readCompositionState(value.run, value.stateFile)); assert.match(result.html, /<div class="slide-body"><h2>Body section<\/h2>/); assert.equal((result.html.match(/<h1>/g) ?? []).length, value.content.slides.length); });
test("rejects nested body h2 and h3 headings", () => { for (const source of ["<h2><h2>x</h2></h2>", "<h2><h3>x</h3></h2>", "<h3><h2>x</h2></h3>", "<h3><h3>x</h3></h3>"]) { const value = prepared(); writeFileSync(bodyPath(value), source); assert.throws(() => validateFragmentSet(value.run, value.content), /FRAGMENT_SYNTAX/); } });
test("checks canonical fragments without renderer or diagnostic side effects", async () => { const value = fixture(), bodies = join(value.run, "slide-bodies"), proof = join(value.root, "proof-log.jsonl"); mkdirSync(bodies); writeFragments(value); await checkComposition(value.run, { chromium:fakeChromium() }); for (const path of [value.stateFile, proof, join(value.run, "index.html"), join(value.run, "slides"), join(value.run, "render-manifest.json")]) assert.equal(existsSync(path), false); writeFileSync(bodyPath(value), "<br>"); await assert.rejects(checkComposition(value.run, { chromium:fakeChromium() }), /FRAGMENT_TAG .*: br/); assert.equal(readFileSync(bodyPath(value), "utf8"), "<br>"); for (const path of [value.stateFile, proof, join(value.run, "index.html"), join(value.run, "slides"), join(value.run, "render-manifest.json")]) assert.equal(existsSync(path), false); });
test("keeps recovered body fragments for the required composition check", async () => { const value = fixture(); mkdirSync(join(value.run, "slide-bodies")); writeFragments(value); prepareRecoveredComposition(value.run, value.stateFile); assert.match(readFileSync(bodyPath(value), "utf8"), /Agent-authored body/); await checkComposition(value.run, { chromium:fakeChromium() }); });
test("keeps the version-2 database contract and gives the composer its exact style boundary", () => { const { value } = loadArchive(), prompt = readFileSync(join(process.cwd(), ".codex/agents/carousel-composer.toml"), "utf8"); assert.equal(value.version, 2); assert.equal(value.id, "database-blueprint"); assert.equal(value.theme, "database"); assert.deepEqual(value.themeAssets, { css:"../../assets/database/theme.css", shell:"../../assets/database/carousel-shell.html" }); assert.deepEqual(value.motifs, ["blueprint"]); assert.deepEqual(value.capabilities, { compositions:["minimal", "editorial", "split", "grid", "flow", "focus"], densities:["sparse", "standard", "dense"], visualAnchors:["headline", "statement", "diagram", "sequence", "contrast", "collection"], directions:["centered", "top-down", "left-right", "radial"] }); assert.equal(Object.hasOwn(value, "fragmentVocabulary"), false); assert.match(prompt, /grid-template-columns/); assert.match(prompt, /border-width\/style\/color/); assert.match(prompt, /var\(\), repeat\(\), minmax\(\)/); assert.doesNotMatch(prompt, /template\.json|theme\.css/); });
test("directs treatment variety through existing direction notes", () => { const director = readFileSync(join(process.cwd(), ".codex/agents/carousel-art-director.toml"), "utf8"), composer = readFileSync(join(process.cwd(), ".codex/agents/carousel-composer.toml"), "utf8"); assert.match(director, /information treatment\s+and reading path/); assert.match(director, /Prefer a different treatment when it improves the slide's semantic\s+relationship, not as forced novelty/); assert.match(director, /directionNote explains the semantic need or deliberate carousel rhythm/); assert.match(director, /repeatJustification does not convey or justify this treatment decision/); assert.match(composer, /information treatment and reading path assigned in that slide's\s+directionNote/); assert.match(composer, /Do not default to a repeated generic card, split, or comparison\s+arrangement/); });
test("preserves every shell-owned field and chrome node for 7/10 slides", () => { for (const count of [7, 10]) { const value = prepared(count), html = validateComposition(value.run, readCompositionState(value.run, value.stateFile)).html, paddedCount = String(count).padStart(2, "0"); for (const slide of value.content.slides) { const number = String(slide.number).padStart(2, "0"); for (const exact of [`data-slide="${slide.number}"`, `<span class="section-label">ACID · ${number}</span>`, `<span class="tag">${slide.role}</span>`, `<h1>${slide.title}</h1>`, `${slide.why}</p>`, `<b class="glossary-term">${slide.glossary[0].term}</b>`, `<span class="glossary-definition">${slide.glossary[0].definition}</span>`, `<span>ACID</span><span>${number} / ${paddedCount}</span>`]) assert.match(html, new RegExp(exact.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))); } assert.equal((html.match(/<span class="brand">db notes<\/span>/g) ?? []).length, count); assert.equal((html.match(/<span class="why-label">Why this matters<\/span>/g) ?? []).length, count); } });
test("accepts multiple roots, all named entities, arbitrary classes, safe SVG, and resource-like prose", () => { const value = prepared(), source = '<div class="invented_name" style="display:flex;position:relative;gap:0;margin:-1px;padding:0;border-width:0 1px;border-style:solid;border-color:#123">JavaScript data: url( &amp; &lt; &gt; &quot; &apos; &#39; &nbsp; &#65; &#x42;</div><figure class="free-diagram"><svg class="diagram-canvas" style="width:100%;fill:none" viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><g style="stroke:#1460AA;stroke-width:2"><line x1="0" y1="0" x2="1000" y2="600"></line></g></svg></figure>'; writeFileSync(bodyPath(value), source); const result = validateComposition(value.run, readCompositionState(value.run, value.stateFile)); assert.equal(result.fragments[0].roots.length, 2); scanHtml(result.html, 7); });
test("accepts representative values from every inline-style group and exact boundary values", () => { const value = prepared(), style = "display:grid;position:relative;grid-template-columns:1fr auto;grid-template-rows:0 10px;grid-column:span 2;grid-row:auto;grid-auto-flow:row dense;flex-direction:row-reverse;flex-wrap:wrap;flex-grow:0;flex-shrink:1.5;flex-basis:auto;order:-1;justify-content:space-between;align-content:stretch;justify-items:center;align-items:start;justify-self:auto;align-self:end;gap:0 1rem;row-gap:0;column-gap:2px;box-sizing:border-box;width:auto;height:0;min-width:auto;min-height:0;max-width:none;max-height:0;inset:auto 1px;top:-1px;right:auto;bottom:0;left:1%;margin:auto -1px 0;margin-top:auto;margin-right:-1em;margin-bottom:0;margin-left:1px;padding:0 1px;padding-top:0;padding-right:1em;padding-bottom:2rem;padding-left:3%;font-family:'IBM Plex Sans', 'Georgia';font-size:1rem;font-weight:700;font-style:italic;line-height:1.2;letter-spacing:-1px;text-align:center;text-transform:uppercase;text-decoration:underline;white-space:pre-wrap;overflow-wrap:anywhere;word-break:keep-all;color:currentcolor;background-color:#fff;border-width:0 1px 2px 3px;border-top-width:0;border-right-width:1px;border-bottom-width:2px;border-left-width:3px;border-style:solid dashed dotted none;border-top-style:none;border-right-style:solid;border-bottom-style:dashed;border-left-style:dotted;border-color:#123 #112233 currentcolor #ABC;border-top-color:#123;border-right-color:#112233;border-bottom-color:currentcolor;border-left-color:#ABC;border-radius:0 1px 2em 3%;fill:none;stroke:#123;stroke-width:1;stroke-linecap:round;stroke-linejoin:bevel"; writeFileSync(bodyPath(value), `<div style="${style}">Styled copy</div>`); assert.equal(validateFragmentSet(value.run, value.content, value.layout).fragments.length, 7); for (const source of ['<svg viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><line style="fill:none;stroke:#123;stroke-width:1" x1="0" y1="0" x2="1" y2="1"></line></svg>', '<svg viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><polyline style="fill:#123;stroke:none" points="0,0 10,0 5,10"></polyline></svg>', '<svg viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><polygon style="fill:none;stroke:#123;stroke-width:1" points="0,0 5,0 10,0"></polygon></svg>', '<div style="width:auto;max-width:none;border-width:0">Zero is visible</div>']) { writeFileSync(bodyPath(value), source); assert.equal(validateFragmentSet(value.run, value.content, value.layout).fragments.length, 7); } });
test("rejects malformed, duplicate, resource-loading, hiding, clipping, and executable style families", () => { const values = ["display:block;;color:#123", "display:block;display:flex", "display: block\n", "color:#123\\9", "color:#123/*x*/", "--x:1", "color:var(--x)", "@import:x", "color:{x}", "color:'red'", "unknown:x", "overflow:hidden", "visibility:hidden", "opacity:0", "content-visibility:hidden", "clip:auto", "clip-path:none", "mask:none", "filter:none", "transform:none", "z-index:1", "content:'x'", "background-image:none", "transition:none", "animation:none", "background:url(x)", "background:javascript:x", "background:vbscript:x", "background:data:x", "behavior:x", "-moz-binding:x", "position:fixed", "position:sticky", "color:transparent", "font-size:0", "font-size:0px", "line-height:0"]; for (const style of values) { const value = prepared(); writeFileSync(bodyPath(value), `<div style="${style}">x</div>`); assert.throws(() => validateFragmentSet(value.run, value.content, value.layout), /FRAGMENT_STYLE/); } });
test("rejects malformed, interactive, resource, reserved-class, empty, and unsafe-style fragments", () => { const invalid = ["text<div>ok</div>", "<div><p>x</div></p>", "<div><!--x--></div>", "<div>&bogus;</div>", "<script>x</script>", '<div data-bind="x">x</div>', '<div onclick="x">x</div>', '<div class="slide-body">x</div>', '<div style="position:fixed">x</div>', '<div style="background-image:url(x)">x</div>', '<div style="overflow:hidden">x</div>', "<div> </div>", '<svg viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"></svg>']; for (const source of invalid) { const value = prepared(); writeFileSync(bodyPath(value), source); assert.throws(() => validateFragmentSet(value.run, value.content, value.layout), /FRAGMENT_(?:SYNTAX|TAG|ATTRIBUTE|CLASS|STYLE|SVG)/); } });
test("rejects reserved and legacy classes, browser repair, namespace drift, unsafe entities, and invisible SVG", () => { const reserved = ["carousel-slide", "slide-content", "masthead", "brand", "section-label", "content", "tag", "why", "why-label", "slide-body", "glossary", "glossary-term", "glossary-definition", "footer", "cp-body"], repairs = ["figure", "figcaption", "li"].map(tag => `<div><p><span><${tag}>repair</${tag}></span></p></div>`), invalid = ['<form>bad</form>', '<iframe>bad</iframe>', '<div href="https://example.com">bad</div>', '<div src="x">bad</div>', '<div><p><span><div>repair</div></span></p></div>', ...repairs, '<line x1="0" y1="0" x2="1" y2="1"></line>', '<g><line x1="0" y1="0" x2="1" y2="1"></line></g>', '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><rect x="0" y="0" width="1" height="1"></rect></svg>', '<svg viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><g><div>namespace</div></g></svg>', '<svg viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><line style="fill:none;stroke:none" x1="0" y1="0" x2="1" y2="1"></line></svg>', '<svg viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><polyline style="fill:#123;stroke:none" points="0,0 10,0"></polyline></svg>', '<svg viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><polygon style="fill:#123;stroke:none" points="0,0 5,0 10,0"></polygon></svg>', '<p>&#128;</p>']; for (const source of [...invalid, ...reserved.map(name => `<div class="${name}">x</div>`)]) { const value = prepared(); writeFileSync(bodyPath(value), source); assert.throws(() => validateFragmentSet(value.run, value.content, value.layout), /FRAGMENT_(?:TAG|ATTRIBUTE|CLASS|SYNTAX|SVG)/); } });
test("rejects missing, extra, nested, misnumbered, non-regular, and symlink fragment entries", () => {
  const cases = [value => rmSync(bodyPath(value)), value => writeFileSync(join(value.run, "slide-bodies", "extra.html"), "x"), value => mkdirSync(join(value.run, "slide-bodies", "nested")), value => { writeFileSync(join(value.run, "slide-bodies", "1.html"), readFileSync(bodyPath(value))); rmSync(bodyPath(value)); }, value => { rmSync(bodyPath(value)); mkdirSync(bodyPath(value)); }, value => { const target = join(value.run, "target.html"); writeFileSync(target, readFileSync(bodyPath(value))); rmSync(bodyPath(value)); symlinkSync(target, bodyPath(value)); }];
  for (const mutate of cases) { const value = prepared(); mutate(value); assert.throws(() => validateFragmentSet(value.run, value.content, value.layout), /COMPOSER_OUTPUT_SET/); }
});
test("rejects oversized, BOM, NUL, and invalid UTF-8 fragment bytes before syntax", () => { for (const bytes of [Buffer.alloc(65537, 32), Buffer.from([0xef, 0xbb, 0xbf, 0x3c]), Buffer.from("<p>\0</p>"), Buffer.from([0xc3, 0x28])]) { const value = prepared(); writeFileSync(bodyPath(value), bytes); assert.throws(() => validateFragmentSet(value.run, value.content, value.layout), /FRAGMENT_BYTES/); } });
test("rejects an unsafe stale body path before composition", () => { const value = fixture(); writeFileSync(join(value.run, "slide-bodies"), "stale"); assert.throws(() => prepareComposition(value.run, value.stateFile), /COMPOSER_STALE_OUTPUT/); });
test("checks every SVG geometry boundary, canonical integer, point, attribute, and element limit", () => {
  const value = fixture(); value.layout.slides[0].visualAnchor = "diagram"; writeFileSync(join(value.run, "carousel-layout.json"), JSON.stringify(value.layout)); prepareComposition(value.run, value.stateFile); writeFragments(value);
  const validShapes = [
    '<line style="stroke:#123;stroke-width:1" x1="0" y1="0" x2="1000" y2="600"></line>', '<polyline style="stroke:#123;stroke-width:1" points="0,0 1000,600"></polyline>', '<polygon style="fill:#123" points="0,0 20,10 0,20"></polygon>',
    '<rect class="diagram-node" style="fill:#123" x="0" y="0" width="1000" height="600" rx="500" ry="300"></rect>', '<circle class="diagram-node" style="fill:#123" cx="300" cy="300" r="300"></circle>', '<ellipse class="diagram-node" style="fill:#123" cx="500" cy="300" rx="500" ry="300"></ellipse>',
  ];
  for (const shape of validShapes) { writeFileSync(bodyPath(value), svgFragment(value.content.slides[0], value.layout.slides[0], shape)); assert.equal(validateFragmentSet(value.run, value.content, value.layout).fragments.length, 7); }
  const line = validShapes[0], tooManyPoints = Array.from({ length:65 }, (_, index) => `${index},${index}`).join(" "), tooManyElements = line.repeat(128), invalidShapes = [line.replace('x2="1000"', 'x2="1001"'), line.replace('x1="0"', 'x1="01"'), line.replace(" x1=", ' transform="x" x1='), `<polyline points="${tooManyPoints}"></polyline>`, '<rect x="0" y="0" width="0" height="1"></rect>', '<rect x="0" y="0" width="10" height="10" rx="6"></rect>', '<circle cx="0" cy="0" r="1"></circle>', '<ellipse cx="1" cy="1" rx="2" ry="1"></ellipse>', '<text></text>', '<path></path>', '<defs></defs>', '<use href="x"></use>', tooManyElements];
  for (const shape of invalidShapes) { writeFileSync(bodyPath(value), svgFragment(value.content.slides[0], value.layout.slides[0], shape)); assert.throws(() => validateFragmentSet(value.run, value.content, value.layout), /FRAGMENT_(?:TAG|ATTRIBUTE|SVG)/); }
  writeFileSync(bodyPath(value), svgFragment(value.content.slides[0], value.layout.slides[0], line.repeat(127))); assert.equal(validateFragmentSet(value.run, value.content, value.layout).fragments.length, 7);
});
test("validates repeat justification but ignores it during composition without warnings", () => { const value = fixture(); value.layout.slides[0].repeatJustification = "Keep the two transaction outcomes comparable."; writeFileSync(join(value.run, "carousel-layout.json"), JSON.stringify(value.layout)); assert.equal(validateLayout(value.run, value.content).slides[0].repeatJustification.length > 0, true); prepareComposition(value.run, value.stateFile); writeFragments(value); const result = validateFragmentSet(value.run, value.content); assert.deepEqual(Object.keys(result), ["fragments"]); for (const invalid of ["", " ", 1, "x".repeat(281)]) { value.layout.slides[0].repeatJustification = invalid; writeFileSync(join(value.run, "carousel-layout.json"), JSON.stringify(value.layout)); assert.throws(() => validateLayout(value.run, value.content), /LAYOUT_NOTE/); } });
test("rejects every closed layout category and exact-shape drift", () => { const mutations = [[value => { value.extra = true; }, "LAYOUT_ROOT_SHAPE"], [value => value.slides.pop(), "LAYOUT_SLIDE_COUNT"], [value => { value.slides[0].extra = true; }, "LAYOUT_SLIDE_SHAPE"], [value => { value.slides[0].number = "1"; }, "LAYOUT_SLIDE_TYPE"], [value => { value.slides[1].number = 1; }, "LAYOUT_SLIDE_IDENTITY"], ...["composition", "density", "visualAnchor", "direction"].map(key => [value => { value.slides[0][key] = "unknown"; }, "LAYOUT_CAPABILITY"]), [value => { value.slides[0].directionNote = "<b>x</b>"; }, "LAYOUT_NOTE"]]; for (const [mutate, code] of mutations) { const value = fixture(); mutate(value.layout); writeFileSync(join(value.run, "carousel-layout.json"), JSON.stringify(value.layout)); assert.throws(() => validateLayout(value.run, value.content), new RegExp(code)); } });
test("protects content, layout, histories, renderer members, arbitrary run entries, archive, shell, and theme", () => {
  const mutations = [
    value => writeFileSync(join(value.run, "carousel-content.json"), `${readFileSync(join(value.run, "carousel-content.json"), "utf8")} `), value => writeFileSync(join(value.run, "carousel-layout.json"), `${readFileSync(join(value.run, "carousel-layout.json"), "utf8")} `),
    value => writeFileSync(join(value.run, "carousel-review-1.json"), "changed"), value => writeFileSync(join(value.run, "index.html"), "changed"), value => mkdirSync(join(value.run, "slides")), value => writeFileSync(join(value.run, "render-manifest.json"), "changed"), value => writeFileSync(join(value.run, "escaped.html"), "changed"), value => rmSync(join(value.run, "request.json")),
  ];
  for (const mutate of mutations) { const value = prepared(); mutate(value); assert.throws(() => validateComposition(value.run, readCompositionState(value.run, value.stateFile)), /COMPOSER_PROTECTED_MUTATION/); }
  for (const path of [join(process.cwd(), "templates/database-blueprint/template.json"), join(process.cwd(), "templates/database-blueprint/preview.html"), join(process.cwd(), "assets/database/carousel-shell.html"), join(process.cwd(), "assets/database/theme.css")]) { const original = readFileSync(path, "utf8"), value = prepared(); try { writeFileSync(path, `${original}\n`); assert.throws(() => validateComposition(value.run, readCompositionState(value.run, value.stateFile)), /COMPOSER_PROTECTED_MUTATION/); } finally { writeFileSync(path, original); } }
});
test("exports complete artifacts and restores all four members after a later failure", async () => {
  const value = fixture(); prepareComposition(value.run, value.stateFile); writeFragments(value); await exportRun(value.run, { chromium:fakeChromium(), stateFile:value.stateFile }); assert.equal(JSON.parse(readFileSync(join(value.run, "render-manifest.json"))).slideCount, 7);
  const before = snapshot(value.run); prepareComposition(value.run, value.stateFile); writeFragments(value); await assert.rejects(exportRun(value.run, { chromium:fakeChromium({ screenshotError:true }), stateFile:value.stateFile })); assert.deepEqual(snapshot(value.run), before);
});
test("restores the original renderer set after a recovered export failure", async () => {
  const value = prepared(); await exportRun(value.run, { chromium:fakeChromium(), stateFile:value.stateFile }); const before = snapshot(value.run);
  const state = prepareComposition(value.run, value.stateFile); writeFragments(value); restoreRenderer(value.run, state);
  writeFragments(value); writeFileSync(bodyPath(value), readFileSync(bodyPath(value), "utf8").replace("Agent-authored", "Recovered"));
  prepareRecoveredComposition(value.run, value.stateFile); await assert.rejects(exportRun(value.run, { chromium:fakeChromium({ screenshotError:true }), stateFile:value.stateFile })); assert.deepEqual(snapshot(value.run), before);
});
test("measures freshly assembled canonical HTML before publication and reports every ordered diagnostic", async () => { const value = prepared(); let measurements = 0; await exportRun(value.run, { chromium:fakeChromium({ onMeasure:() => measurements++ }), stateFile:value.stateFile }); assert.equal(measurements, 2); const changed = prepared(), inputs = []; await assert.rejects(exportRun(changed.run, { chromium:fakeChromium({ onSetContent:html => inputs.push(html), onScreenshot:({ slide }) => { if (slide === 1) writeFileSync(bodyPath(changed), readFileSync(bodyPath(changed), "utf8").replace("Agent-authored", "Freshly assembled")); } }), stateFile:changed.stateFile }), /ASSEMBLY_FIDELITY/); assert.match(inputs[1], /Freshly assembled/); const diagnostics = ["BODY_OVERFLOW slide 1 /body: reserved body overflow", "BODY_OVERFLOW slide 3 /body: reserved body overflow", "BODY_UNDERFILL slide 1 /body: qualifying span 0", "BODY_UNDERFILL slide 2 /body: qualifying span 0"]; const failed = prepared(); await assert.rejects(exportRun(failed.run, { chromium:fakeChromium({ violation:diagnostics }), stateFile:failed.stateFile }), error => error.message === diagnostics.join("\n")); });
test("restores all four members after protected, fragment, browser, export, fidelity, and publication failures", async () => {
  const publish = async () => { const value = prepared(); await exportRun(value.run, { chromium:fakeChromium(), stateFile:value.stateFile }); return value; }, failAfterPrepare = async (configure, chromium = fakeChromium()) => { const value = await publish(), before = snapshot(value.run); prepareComposition(value.run, value.stateFile); writeFragments(value); await configure(value); await assert.rejects(exportRun(value.run, { chromium, stateFile:value.stateFile })); assert.deepEqual(snapshot(value.run), before); };
  await failAfterPrepare(value => writeFileSync(join(value.run, "escaped.html"), "mutation"));
  await failAfterPrepare(value => writeFileSync(bodyPath(value), readFileSync(bodyPath(value), "utf8").replace("<section", '<section data-bind="x"')));
  await failAfterPrepare(() => {}, fakeChromium({ violation:["BODY_OVERFLOW slide 1 /body: reserved body overflow"] }));
  await failAfterPrepare(() => {}, fakeChromium({ violation:["BODY_UNDERFILL slide 1 /body: qualifying span 0.699"] }));
  await failAfterPrepare(() => {}, fakeChromium({ image:Buffer.from("not png") }));
  { const value = await publish(), before = snapshot(value.run); prepareComposition(value.run, value.stateFile); writeFragments(value); const chromium = fakeChromium({ onScreenshot:({ slide }) => { if (slide === 1) writeFileSync(bodyPath(value), readFileSync(bodyPath(value), "utf8").replace("Agent-authored", "Mutated")); } }); await assert.rejects(exportRun(value.run, { chromium, stateFile:value.stateFile }), /ASSEMBLY_FIDELITY/); assert.deepEqual(snapshot(value.run), before); }
  { const value = await publish(), before = snapshot(value.run); prepareComposition(value.run, value.stateFile); writeFragments(value); const chromium = fakeChromium({ onScreenshot:({ slide }) => { if (slide === 7) { rmSync(join(value.run, "index.html")); mkdirSync(join(value.run, "index.html")); } } }); await assert.rejects(exportRun(value.run, { chromium, stateFile:value.stateFile })); assert.deepEqual(snapshot(value.run), before); }
});
test("withholds the manifest through capture and installs it only on successful publication", async () => { const value = prepared(); let captures = 0; await exportRun(value.run, { stateFile:value.stateFile, chromium:fakeChromium({ onScreenshot:() => { captures++; assert.equal(existsSync(join(value.run, "render-manifest.json")), false); } }) }); assert.equal(captures, 7); assert.equal(existsSync(join(value.run, "render-manifest.json")), true); });
test("removes every candidate member after a first-render failure", async () => { const value = prepared(); await assert.rejects(exportRun(value.run, { chromium:fakeChromium({ violation:["BODY_OVERFLOW slide 2 /body/0: crossed right"] }), stateFile:value.stateFile }), /BODY_OVERFLOW/); for (const name of ["slide-bodies", "index.html", "slides", "render-manifest.json"]) assert.equal(existsSync(join(value.run, name)), false); });
test("real Chromium contains an unbroken shell-owned glossary term", async t => {
  const { chromium } = await import("playwright"); if (!existsSync(chromium.executablePath())) return t.skip("Run npx playwright install chromium once.");
  const value = fixture(); value.content.slides[0].glossary[0].term = "Interoperability"; writeFileSync(join(value.run, "carousel-content.json"), JSON.stringify(value.content)); prepareComposition(value.run, value.stateFile); writeFragments(value); const composed = validateComposition(value.run, readCompositionState(value.run, value.stateFile));
  try { await inspectDom(composed.html, 7, { chromium }); }
  catch (error) { if (/browserType\.launch/.test(error.message)) return t.skip("Chromium cannot launch in this sandbox."); throw error; }
});
test("real Chromium measures text and painted SVG body spans", async t => {
  const { chromium } = await import("playwright"); if (!existsSync(chromium.executablePath())) return t.skip("Run npx playwright install chromium once.");
  const value = prepared(); const htmlFor = source => { value.content.slides.forEach((_, index) => writeFileSync(bodyPath(value, index), source)); return validateComposition(value.run, readCompositionState(value.run, value.stateFile)).html; };
  const inspect = html => inspectDom(html, value.content.slides.length, { chromium });
  try {
    await assert.doesNotReject(inspect(htmlFor(spanSvg("70"))));
    writeFileSync(bodyPath(value), spanSvg("69.9")); await assert.rejects(inspect(validateComposition(value.run, readCompositionState(value.run, value.stateFile)).html), /BODY_UNDERFILL slide 1/);
    for (const source of [wrapper, shallow, '<svg style="display:block;width:100%;height:100%" viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false"><g><rect style="fill:#123" x="0" y="0" width="10" height="10"></rect></g></svg>']) await assert.rejects(inspect(htmlFor(source)), /BODY_UNDERFILL/);
    for (const source of [fragment(), '<ol style="display:flex;height:100%;flex-direction:column;justify-content:space-between"><li>First ordered step</li><li>Second ordered step</li><li>Third ordered step</li></ol>', '<section style="display:flex;height:100%;flex-direction:column;justify-content:space-between"><p>Left choice</p><p>Right consequence</p></section>', spanSvg("70")]) await assert.doesNotReject(inspect(htmlFor(source)));
    const clipped = await rejected(() => inspect(htmlFor(spanSvg("120")))); assert.match(clipped.message, /BODY_OVERFLOW/); assert.doesNotMatch(clipped.message, /BODY_UNDERFILL/);
    writeFileSync(bodyPath(value), '<p style="position:relative;top:999px">Escaped text</p>'); writeFileSync(bodyPath(value, 1), wrapper); const error = await rejected(() => inspect(validateComposition(value.run, readCompositionState(value.run, value.stateFile)).html)); assert.ok(error.message.indexOf("BODY_OVERFLOW slide 1") < error.message.indexOf("BODY_UNDERFILL slide 1"));
  } catch (error) { if (/browserType\.launch/.test(error.message)) return t.skip("Chromium cannot launch in this sandbox."); throw error; }
});
test("real Chromium exports inspectable 7/10 runs and exercises reserved-body containment", async t => {
  const { chromium } = await import("playwright"); if (!existsSync(chromium.executablePath())) return t.skip("Run npx playwright install chromium once.");
  const proofRoot = process.env.APOLLO_PROOF_OUTPUT; for (const count of [7, 10]) {
    const value = fixture(count, proofRoot ? { root:proofRoot, runId:`proof-${count}` } : undefined); value.layout.slides[0].visualAnchor = "diagram"; writeFileSync(join(value.run, "carousel-layout.json"), JSON.stringify(value.layout)); prepareComposition(value.run, value.stateFile); writeFragments(value); const composed = validateComposition(value.run, readCompositionState(value.run, value.stateFile));
    try { await inspectDom(composed.html, count, { chromium }); }
    catch (error) { if (/browserType\.launch/.test(error.message)) return t.skip("Chromium cannot launch in this sandbox."); throw error; }
    if (count === 7) {
      const cases = [[".slide-body", "display:none", "/body"], [".free-flow", "width:1200px", "/body/0"], [".free-flow", "height:1200px", "/body/0"], [".free-flow", "position:relative;left:-8px", "/body/0"], [".free-flow", "position:relative;left:8px", "/body/0"], [".free-flow", "position:relative;top:-8px", "/body/0"], [".free-flow", "position:relative;top:8px", "/body/0"], [".novel-card", "position:absolute;left:-100px", "/body/0/0"], [".novel-card p", "position:relative;left:-100px", "/body/0/0/1"], [".novel-card p", "display:none", "/body/0/0/1"], [".novel-card p", "visibility:hidden", "/body/0/0/1"], [".novel-card p", "content-visibility:hidden", "/body/0/0/1"], [".novel-card p", "opacity:0", "/body/0/0/1"], [".novel-card", "overflow:hidden", "/body/0/0"], [".novel-card", "clip-path:inset(1px)", "/body/0/0"], [".novel-card p", "font-size:0", "/body/0/0/1"], [".novel-card p", "line-height:0", "/body/0/0/1"], [".novel-card p", "color:rgba(0,0,0,0)", "/body/0/0/1"]];
      for (const [selector, css, message] of cases) { const html = composed.html.replace("</style>", `[data-slide=\"1\"] ${selector}{${css}}</style>`); await assert.rejects(inspectDom(html, count, { chromium }), new RegExp(`BODY_OVERFLOW slide 1 ${message.replaceAll("/", "\\/")}`)); }
      await assert.doesNotReject(inspectDom(composed.html.replace("</style>", '[data-slide="1"] .novel-card{font-family:system-ui,sans-serif}</style>'), count, { chromium }));
      await assert.rejects(inspectDom(composed.html.replace("</style>", '[data-slide="1"] .novel-card{background-image:url(https://invalid.example/font.woff2)}</style>'), count, { chromium }), /RENDER_EXPORT: network route attempted/);
      writeFileSync(bodyPath(value), svgFragment(value.content.slides[0], value.layout.slides[0], '<line class="diagram-line" style="stroke:#1460AA;stroke-width:2" x1="20" y1="20" x2="980" y2="580"></line>')); const svgComposed = validateComposition(value.run, readCompositionState(value.run, value.stateFile)); await assert.rejects(inspectDom(svgComposed.html.replace("</style>", '[data-slide="1"] .diagram-line{fill:none!important;stroke:none!important}</style>'), count, { chromium }), /BODY_OVERFLOW slide 1 \/body\/0\/1\/0/);
    }
    if (count !== 7) writeFileSync(bodyPath(value), svgFragment(value.content.slides[0], value.layout.slides[0], '<line class="diagram-line" style="stroke:#1460AA;stroke-width:2" x1="20" y1="20" x2="980" y2="580"></line>')); await exportRun(value.run, { chromium, stateFile:value.stateFile }); const manifest = JSON.parse(readFileSync(join(value.run, "render-manifest.json"), "utf8")); assert.equal(manifest.slideCount, count); assert.equal(manifest.slides.length, count); manifest.slides.forEach(path => assert.deepEqual(pngSize(join(value.run, path)), { width:1080, height:1350 })); if (proofRoot) console.log(`Inspectable proof run: ${value.run}`);
  }
});

function snapshot(run) { const visit = path => Object.fromEntries(readdirSync(path, { withFileTypes:true }).sort((a,b) => a.name.localeCompare(b.name)).map(entry => [entry.name, entry.isDirectory() ? visit(join(path, entry.name)) : readFileSync(join(path, entry.name)).toString("base64")])); return Object.fromEntries(["slide-bodies", "index.html", "slides", "render-manifest.json"].map(name => [name, statValue(join(run, name), visit)])); }
function statValue(path, visit) { return isDirectory(path) ? visit(path) : readFileSync(path).toString("base64"); }
function isDirectory(path) { try { return readdirSync(path), true; } catch { return false; } }
